# 비워둠
spring:
  cloud:
    gateway:
      routes:
        # - id: msa-user
        #   uri: http://localhost:8080
        #   predicates:
        #     - Path=/member/login
        #   filters:
        #     - CreateTokenFilter  # 필요시 인증/인가 필터 추가
        - id: msa-portfolio
          uri: http://portfolio-service:3001
          predicates:
            - Path=/portfolio/**
          filters:
            - AuthorizationHeaderFilter  # 필요시 인증/인가 필터 추가
        - id: msa-notice
          uri: http://notice-service:8080
          predicates:
            - Path=/notice/**
          filters:
            - AuthorizationHeaderFilter  # 필요시 인증/인가 필터 추가
jwt:
  # HS512알고리즘을 사용할 것이기 때문에 512bit, 즉 64byte이상의 secret key를 사용해야 한다.
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  token-validity-in-seconds: 86400000 # 만료기간 1일

server:
  port: 8081