spring:
  cloud:
    gateway:
      routes:
        - id: msa-portfolio
          uri: ${SPRING_CLOUD_GATEWAY_ROUTES_0_URI}
          predicates:
            - Path=${SPRING_CLOUD_GATEWAY_ROUTES_0_PREDICATES_0}
          filters:
            - ${SPRING_CLOUD_GATEWAY_ROUTES_0_FILTERS_0}
        - id: msa-notice
          uri: ${SPRING_CLOUD_GATEWAY_ROUTES_1_URI}
          predicates:
            - Path=${SPRING_CLOUD_GATEWAY_ROUTES_1_PREDICATES_0}
          filters:
            - ${SPRING_CLOUD_GATEWAY_ROUTES_1_FILTERS_0}
server:
  port: ${SERVER_PORT}
jwt:
  token-validity-in-seconds: ${JWT_TOKEN_VALIDITY_IN_SECONDS}
  secret: ${JWT_SECRET}
